spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false

looky:
  result-generation:
    s3:
      bucket: ${LOOKY_RESULT_S3_BUCKET}
      region: ${AWS_REGION:ap-northeast-2}
