create table surveys (id bigint auto_increment primary key,user_nickname varchar(40) not null,survey_code varchar(12) not null unique,survey_status varchar(32) not null,result_status varchar(64) not null,result_generation_attempt_count int not null default 0,required_peer_submission_count int not null,result_available_at timestamp with time zone not null,closed_at timestamp with time zone,expires_at timestamp with time zone,created_at timestamp with time zone not null,updated_at timestamp with time zone not null);
create table questions (id bigint auto_increment primary key,content_self text not null,content_peer text not null,question_type varchar(40) not null,trait_code varchar(40) not null,active boolean not null,created_at timestamp with time zone not null,updated_at timestamp with time zone not null);
create table answer_options (id bigint auto_increment primary key,question_id bigint not null,content_self text not null,content_peer text not null,sequence int not null,active boolean not null,created_at timestamp with time zone not null,updated_at timestamp with time zone not null,unique(question_id,sequence),foreign key(question_id) references questions(id));
create table submissions (id bigint auto_increment primary key,survey_id bigint not null,submitter_type varchar(20) not null,submitter_key varchar(80) not null,submission_status varchar(20) not null,started_at timestamp with time zone not null,submitted_at timestamp with time zone,created_at timestamp with time zone not null,updated_at timestamp with time zone not null,unique(survey_id,submitter_key),foreign key(survey_id) references surveys(id));
create table submission_questions (id bigint auto_increment primary key,submission_id bigint not null,question_id bigint not null,sequence int not null,question_content_snapshot text not null,created_at timestamp with time zone not null,unique(submission_id,question_id),unique(submission_id,sequence),foreign key(submission_id) references submissions(id),foreign key(question_id) references questions(id));
create table submission_answers (id bigint auto_increment primary key,submission_question_id bigint not null unique,answer_option_id bigint not null,answer_content_snapshot text not null,created_at timestamp with time zone not null,foreign key(submission_question_id) references submission_questions(id),foreign key(answer_option_id) references answer_options(id));
create table results (id bigint auto_increment primary key,survey_id bigint not null unique,created_at timestamp with time zone not null,updated_at timestamp with time zone not null,foreign key(survey_id) references surveys(id));
create table result_quadrants (id bigint auto_increment primary key,result_id bigint not null,quadrant_type varchar(32) not null,image_url varchar(2048),interpretation text,image_prompt text,s3_object_key varchar(1024),work_status varchar(32) not null,attempt_count int not null default 0,failure_reason text,unique(result_id,quadrant_type),foreign key(result_id) references results(id));
create table result_answer_adjectives (id bigint auto_increment primary key,result_id bigint not null,submission_answer_id bigint not null,question_id bigint not null,trait_code varchar(40) not null,question_snapshot text not null,answer_snapshot text not null,adjectives_json text not null,unique(result_id,submission_answer_id),foreign key(result_id) references results(id));
