set @content_self_template_column_exists = (
    select count(*)
    from information_schema.columns
    where table_schema = database()
      and table_name = 'questions'
      and column_name = 'content_self_template'
);
set @add_content_self_template_column = if(
    @content_self_template_column_exists = 0,
    'alter table questions add column content_self_template text',
    'select 1'
);
prepare add_content_self_template_column_stmt from @add_content_self_template_column;
execute add_content_self_template_column_stmt;
deallocate prepare add_content_self_template_column_stmt;

set @content_peer_template_column_exists = (
    select count(*)
    from information_schema.columns
    where table_schema = database()
      and table_name = 'questions'
      and column_name = 'content_peer_template'
);
set @add_content_peer_template_column = if(
    @content_peer_template_column_exists = 0,
    'alter table questions add column content_peer_template text',
    'select 1'
);
prepare add_content_peer_template_column_stmt from @add_content_peer_template_column;
execute add_content_peer_template_column_stmt;
deallocate prepare add_content_peer_template_column_stmt;

delete from answer_options where question_id in (select id from questions);
delete from questions;

insert into questions (id, content_self, content_peer, content_self_template, content_peer_template, question_type, trait_code, active, created_at, updated_at) values
(1, '“내일 1박2일 여행 ㄱ?” 라는 메세지를 받았다 나라면?', '“내일 1박2일 여행 ㄱ?” 라는 메세지를 받았다 나라면?', '“내일 1박2일 여행 ㄱ?” 라는 메세지를 받았다 {나:이라면}?', '“내일 1박2일 여행 ㄱ?” 라는 메세지를 받았다 {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(2, '잡아둔 약속이 당일날 엎어졌다. 나라면?', '잡아둔 약속이 당일날 엎어졌다. 나라면?', '잡아둔 약속이 당일날 엎어졌다. {나:이라면}?', '잡아둔 약속이 당일날 엎어졌다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(3, '새로 나온 앱·기기·트렌드를 봤다. 나라면?', '새로 나온 앱·기기·트렌드를 봤다. 나라면?', '새로 나온 앱·기기·트렌드를 봤다. {나:이라면}?', '새로 나온 앱·기기·트렌드를 봤다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(4, '나의 책·영화 취향은?', '나의 책·영화 취향은?', '{나:의} 책·영화 취향은?', '{나:의} 책·영화 취향은?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(5, '이사·전학·이직 같은 큰 변화 앞에서 나라면?', '이사·전학·이직 같은 큰 변화 앞에서 나라면?', '이사·전학·이직 같은 큰 변화 앞에서 {나:이라면}?', '이사·전학·이직 같은 큰 변화 앞에서 {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(6, '안 해본 운동이나 액티비티를 권유받았을 때 나라면?', '안 해본 운동이나 액티비티를 권유받았을 때 나라면?', '안 해본 운동이나 액티비티를 권유받았을 때 {나:이라면}?', '안 해본 운동이나 액티비티를 권유받았을 때 {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(7, '익숙한 길 vs 처음 가보는 길, 나라면?', '익숙한 길 vs 처음 가보는 길, 나라면?', '익숙한 길 vs 처음 가보는 길, {나:이라면}?', '익숙한 길 vs 처음 가보는 길, {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(8, '처음 보는 사람들과 어울리는 자리에서 나라면?', '처음 보는 사람들과 어울리는 자리에서 나라면?', '처음 보는 사람들과 어울리는 자리에서 {나:이라면}?', '처음 보는 사람들과 어울리는 자리에서 {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(9, '먹어보지 않은 나라 음식에 대한 나의 태도는?', '먹어보지 않은 나라 음식에 대한 나의 태도는?', '먹어보지 않은 나라 음식에 대한 {나:의} 태도는?', '먹어보지 않은 나라 음식에 대한 {나:의} 태도는?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(10, '규칙·관습을 대할 때 나의 태도는?', '규칙·관습을 대할 때 나의 태도는?', '규칙·관습을 대할 때 {나:의} 태도는?', '규칙·관습을 대할 때 {나:의} 태도는?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(11, '나는 남들이 하는 대로 따라하는 편인가?', '나는 남들이 하는 대로 따라하는 편인가?', '{나:은는} 남들이 하는 대로 따라하는 편인가?', '{나:은는} 남들이 하는 대로 따라하는 편인가?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(12, '생소한 새 직무·역할 제안이 들어왔다. 나라면?', '생소한 새 직무·역할 제안이 들어왔다. 나라면?', '생소한 새 직무·역할 제안이 들어왔다. {나:이라면}?', '생소한 새 직무·역할 제안이 들어왔다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(13, '나에게 도전리스트란?', '나에게 도전리스트란?', '{나:에게} 도전리스트란?', '{나:에게} 도전리스트란?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(14, '영상·음악 콘텐츠를 고를 때 나라면?', '영상·음악 콘텐츠를 고를 때 나라면?', '영상·음악 콘텐츠를 고를 때 {나:이라면}?', '영상·음악 콘텐츠를 고를 때 {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(15, '자주가는 약속 장소 가는 길에 시간이 30분쯤 붕 떴다. 나라면?', '자주가는 약속 장소 가는 길에 시간이 30분쯤 붕 떴다. 나라면?', '자주가는 약속 장소 가는 길에 시간이 30분쯤 붕 떴다. {나:이라면}?', '자주가는 약속 장소 가는 길에 시간이 30분쯤 붕 떴다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(16, '내가 새 학기 동아리를 고르는 상황이라면?', '내가 새 학기 동아리를 고르는 상황이라면?', '{나:이가} 새 학기 동아리를 고르는 상황이라면?', '{나:이가} 새 학기 동아리를 고르는 상황이라면?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(17, '어딘가로 떠나기로 했다. 나의 짐싸기 모습은?', '어딘가로 떠나기로 했다. 나의 짐싸기 모습은?', '어딘가로 떠나기로 했다. {나:의} 짐싸기 모습은?', '어딘가로 떠나기로 했다. {나:의} 짐싸기 모습은?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(18, '빈 주말이 통째로 생겼다. 나라면?', '빈 주말이 통째로 생겼다. 나라면?', '빈 주말이 통째로 생겼다. {나:이라면}?', '빈 주말이 통째로 생겼다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(19, '갑자기 핫해진 새 트렌드가 눈에 들어왔다. 나라면?', '갑자기 핫해진 새 트렌드가 눈에 들어왔다. 나라면?', '갑자기 핫해진 새 트렌드가 눈에 들어왔다. {나:이라면}?', '갑자기 핫해진 새 트렌드가 눈에 들어왔다. {나:이라면}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(20, '매일 다람쥐 쳇바퀴 같은 일상 속 나는?', '매일 다람쥐 쳇바퀴 같은 일상 속 나는?', '매일 다람쥐 쳇바퀴 같은 일상 속 {나:은는}?', '매일 다람쥐 쳇바퀴 같은 일상 속 {나:은는}?', 'SITUATION_5_CHOICE', 'OPENNESS', true, current_timestamp, current_timestamp),
(21, '새 할 일이 떨어졌을 때 나라면?', '새 할 일이 떨어졌을 때 나라면?', '새 할 일이 떨어졌을 때 {나:이라면}?', '새 할 일이 떨어졌을 때 {나:이라면}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(22, '나의 책상·방·가방 속은?', '나의 책상·방·가방 속은?', '{나:의} 책상·방·가방 속은?', '{나:의} 책상·방·가방 속은?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(23, '일을 시작하기 직전 나의 모습은?', '일을 시작하기 직전 나의 모습은?', '일을 시작하기 직전 {나:의} 모습은?', '일을 시작하기 직전 {나:의} 모습은?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(24, '맡은 일의 마무리를 봤을때 나는?', '맡은 일의 마무리를 봤을때 나는?', '맡은 일의 마무리를 봤을때 {나:은는}?', '맡은 일의 마무리를 봤을때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(25, '약속 시간에 나의 모습은?', '약속 시간에 나의 모습은?', '약속 시간에 {나:의} 모습은?', '약속 시간에 {나:의} 모습은?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(26, '마감이 코앞일 때 나의 모습은?', '마감이 코앞일 때 나의 모습은?', '마감이 코앞일 때 {나:의} 모습은?', '마감이 코앞일 때 {나:의} 모습은?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(27, '나의 디테일 캐치 능력은?', '나의 디테일 캐치 능력은?', '{나:의} 디테일 캐치 능력은?', '{나:의} 디테일 캐치 능력은?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(28, '약속과 할 일을 관리할 때 나는?', '약속과 할 일을 관리할 때 나는?', '약속과 할 일을 관리할 때 {나:은는}?', '약속과 할 일을 관리할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(29, '내 일에서 실수를 발견했을 때 나는?', '내 일에서 실수를 발견했을 때 나는?', '{나:의} 일에서 실수를 발견했을 때 {나:은는}?', '{나:의} 일에서 실수를 발견했을 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(30, '돈과 일정 관리를 봤을때 나는?', '돈과 일정 관리를 봤을때 나는?', '돈과 일정 관리를 봤을때 {나:은는}?', '돈과 일정 관리를 봤을때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(31, '규칙과 약속을 대할 때 나는?', '규칙과 약속을 대할 때 나는?', '규칙과 약속을 대할 때 {나:은는}?', '규칙과 약속을 대할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(32, '정리정돈을 할 때 나는?', '정리정돈을 할 때 나는?', '정리정돈을 할 때 {나:은는}?', '정리정돈을 할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(33, '일의 우선순위를 정할 때 나는?', '일의 우선순위를 정할 때 나는?', '일의 우선순위를 정할 때 {나:은는}?', '일의 우선순위를 정할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(34, '여행 짐을 쌀 때 나는?', '여행 짐을 쌀 때 나는?', '여행 짐을 쌀 때 {나:은는}?', '여행 짐을 쌀 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(35, '정해진 절차나 매뉴얼 앞에서 나는?', '정해진 절차나 매뉴얼 앞에서 나는?', '정해진 절차나 매뉴얼 앞에서 {나:은는}?', '정해진 절차나 매뉴얼 앞에서 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(36, '운동·공부 새 습관을 시작하면 나는?', '운동·공부 새 습관을 시작하면 나는?', '운동·공부 새 습관을 시작하면 {나:은는}?', '운동·공부 새 습관을 시작하면 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(37, '내 방이나 자리를 보면 나는?', '내 방이나 자리를 보면 나는?', '{나:의} 방이나 자리를 보면 {나:은는}?', '{나:의} 방이나 자리를 보면 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(38, '뭔가 살까 말까 고민될 때 나는?', '뭔가 살까 말까 고민될 때 나는?', '뭔가 살까 말까 고민될 때 {나:은는}?', '뭔가 살까 말까 고민될 때 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(39, '새 목표가 생기면 나는?', '새 목표가 생기면 나는?', '새 목표가 생기면 {나:은는}?', '새 목표가 생기면 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(40, '책상이나 폰 바탕화면을 보면 나는?', '책상이나 폰 바탕화면을 보면 나는?', '책상이나 폰 바탕화면을 보면 {나:은는}?', '책상이나 폰 바탕화면을 보면 {나:은는}?', 'SITUATION_5_CHOICE', 'CONSCIENTIOUSNESS', true, current_timestamp, current_timestamp),
(41, '아는 사람 없는 모임, 30분 뒤 나는?', '아는 사람 없는 모임, 30분 뒤 나는?', '아는 사람 없는 모임, 30분 뒤 {나:은는}?', '아는 사람 없는 모임, 30분 뒤 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(42, '아무 약속 없는 주말, 나의 모습은?', '아무 약속 없는 주말, 나의 모습은?', '아무 약속 없는 주말, {나:의} 모습은?', '아무 약속 없는 주말, {나:의} 모습은?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(43, '발표 차례로 시선이 쏠릴 때 나는?', '발표 차례로 시선이 쏠릴 때 나는?', '발표 차례로 시선이 쏠릴 때 {나:은는}?', '발표 차례로 시선이 쏠릴 때 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(44, '많은 사람 앞에 서는 순간 나는?', '많은 사람 앞에 서는 순간 나는?', '많은 사람 앞에 서는 순간 {나:은는}?', '많은 사람 앞에 서는 순간 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(45, '큰 행사·파티 초대장이 오면 나의 선택은?', '큰 행사·파티 초대장이 오면 나의 선택은?', '큰 행사·파티 초대장이 오면 {나:의} 선택은?', '큰 행사·파티 초대장이 오면 {나:의} 선택은?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(46, '처음 만난 사람과 마주 앉으면 나는?', '처음 만난 사람과 마주 앉으면 나는?', '처음 만난 사람과 마주 앉으면 {나:은는}?', '처음 만난 사람과 마주 앉으면 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(47, '노래방·게임처럼 나서야 할 때 나는?', '노래방·게임처럼 나서야 할 때 나는?', '노래방·게임처럼 나서야 할 때 {나:은는}?', '노래방·게임처럼 나서야 할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(48, '모르는 사람에게 길을 물어야 할 때 나는?', '모르는 사람에게 길을 물어야 할 때 나는?', '모르는 사람에게 길을 물어야 할 때 {나:은는}?', '모르는 사람에게 길을 물어야 할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(49, '평소 텐션을 한마디로 하면 나는?', '평소 텐션을 한마디로 하면 나는?', '평소 텐션을 한마디로 하면 {나:은는}?', '평소 텐션을 한마디로 하면 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(50, '조용한 카페 vs 북적이는 술집, 나의 선택은?', '조용한 카페 vs 북적이는 술집, 나의 선택은?', '조용한 카페 vs 북적이는 술집, {나:의} 선택은?', '조용한 카페 vs 북적이는 술집, {나:의} 선택은?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(51, '나의  첫인상은?', '나의  첫인상은?', '{나:의}  첫인상은?', '{나:의}  첫인상은?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(52, '처음 본 사람과 종일 있은 뒤 나는?', '처음 본 사람과 종일 있은 뒤 나는?', '처음 본 사람과 종일 있은 뒤 {나:은는}?', '처음 본 사람과 종일 있은 뒤 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(53, '문득 누가 보고 싶어질 때 나는?', '문득 누가 보고 싶어질 때 나는?', '문득 누가 보고 싶어질 때 {나:은는}?', '문득 누가 보고 싶어질 때 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(54, '처음 보는 사람들 앞 자기소개, 나라면?', '처음 보는 사람들 앞 자기소개, 나라면?', '처음 보는 사람들 앞 자기소개, {나:이라면}?', '처음 보는 사람들 앞 자기소개, {나:이라면}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(55, '모임에서 주목받는 순간 나는?', '모임에서 주목받는 순간 나는?', '모임에서 주목받는 순간 {나:은는}?', '모임에서 주목받는 순간 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(56, '모르는 사람과 한 공간에 있다면 나는?', '모르는 사람과 한 공간에 있다면 나는?', '모르는 사람과 한 공간에 있다면 {나:은는}?', '모르는 사람과 한 공간에 있다면 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(57, '하루에 약속이 세 개 겹치면 나는?', '하루에 약속이 세 개 겹치면 나는?', '하루에 약속이 세 개 겹치면 {나:은는}?', '하루에 약속이 세 개 겹치면 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(58, '회식 자리에서 나는?', '회식 자리에서 나는?', '회식 자리에서 {나:은는}?', '회식 자리에서 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(59, '새 친구 한 명이 생기기까지 나는?', '새 친구 한 명이 생기기까지 나는?', '새 친구 한 명이 생기기까지 {나:은는}?', '새 친구 한 명이 생기기까지 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(60, '일상적인 단톡방에서 나는?', '일상적인 단톡방에서 나는?', '일상적인 단톡방에서 {나:은는}?', '일상적인 단톡방에서 {나:은는}?', 'SITUATION_5_CHOICE', 'EXTRAVERSION', true, current_timestamp, current_timestamp),
(61, '새벽 2시 힘들다는 톡을 받으면 나는?', '새벽 2시 힘들다는 톡을 받으면 나는?', '새벽 2시 힘들다는 톡을 받으면 {나:은는}?', '새벽 2시 힘들다는 톡을 받으면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(62, '좀 귀찮은 부탁을 받으면 나는?', '좀 귀찮은 부탁을 받으면 나는?', '좀 귀찮은 부탁을 받으면 {나:은는}?', '좀 귀찮은 부탁을 받으면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(63, '누가 실수로 안절부절못할 때 나라면?', '누가 실수로 안절부절못할 때 나라면?', '누가 실수로 안절부절못할 때 {나:이라면}?', '누가 실수로 안절부절못할 때 {나:이라면}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(64, '평소 말투를 봤을때 나는?', '평소 말투를 봤을때 나는?', '평소 말투를 봤을때 {나:은는}?', '평소 말투를 봤을때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(65, '단체 의견이 갈려 분위기가 싸할 때 나는?', '단체 의견이 갈려 분위기가 싸할 때 나는?', '단체 의견이 갈려 분위기가 싸할 때 {나:은는}?', '단체 의견이 갈려 분위기가 싸할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(66, '처음 보는 사람과 한 팀이 되면 나라면?', '처음 보는 사람과 한 팀이 되면 나라면?', '처음 보는 사람과 한 팀이 되면 {나:이라면}?', '처음 보는 사람과 한 팀이 되면 {나:이라면}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(67, '모르는 사람이 짐을 들고 낑낑댈 때 나는?', '모르는 사람이 짐을 들고 낑낑댈 때 나는?', '모르는 사람이 짐을 들고 낑낑댈 때 {나:은는}?', '모르는 사람이 짐을 들고 낑낑댈 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(68, '누군가의 잘못을 짚어야 할 때 나는?', '누군가의 잘못을 짚어야 할 때 나는?', '누군가의 잘못을 짚어야 할 때 {나:은는}?', '누군가의 잘못을 짚어야 할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(69, '누가 무리한 요구를 들이밀면 나는?', '누가 무리한 요구를 들이밀면 나는?', '누가 무리한 요구를 들이밀면 {나:은는}?', '누가 무리한 요구를 들이밀면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(70, '모임에서 혼자 겉도는 사람이 보이면 나는?', '모임에서 혼자 겉도는 사람이 보이면 나는?', '모임에서 혼자 겉도는 사람이 보이면 {나:은는}?', '모임에서 혼자 겉도는 사람이 보이면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(71, '내가 조금 손해 보는 상황이면 나는?', '내가 조금 손해 보는 상황이면 나는?', '{나:이가} 조금 손해 보는 상황이면 {나:은는}?', '{나:이가} 조금 손해 보는 상황이면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(72, '내 의견에 누가 대놓고 반대한다면 나는?', '내 의견에 누가 대놓고 반대한다면 나는?', '{나:의} 의견에 누가 대놓고 반대한다면 {나:은는}?', '{나:의} 의견에 누가 대놓고 반대한다면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(73, '팀에 아무도 안 하려는 일이 오면 나는?', '팀에 아무도 안 하려는 일이 오면 나는?', '팀에 아무도 안 하려는 일이 오면 {나:은는}?', '팀에 아무도 안 하려는 일이 오면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(74, '양보냐 고집이냐 갈림길에서 나는?', '양보냐 고집이냐 갈림길에서 나는?', '양보냐 고집이냐 갈림길에서 {나:은는}?', '양보냐 고집이냐 갈림길에서 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(75, '단톡방에 부탁에 대답이 없으면 나는?', '단톡방에 부탁에 대답이 없으면 나는?', '단톡방에 부탁에 대답이 없으면 {나:은는}?', '단톡방에 부탁에 대답이 없으면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(76, '상대 표정이 평소와 다를 때 나는?', '상대 표정이 평소와 다를 때 나는?', '상대 표정이 평소와 다를 때 {나:은는}?', '상대 표정이 평소와 다를 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(77, '부탁을 꼭 거절해야 할 때 나는?', '부탁을 꼭 거절해야 할 때 나는?', '부탁을 꼭 거절해야 할 때 {나:은는}?', '부탁을 꼭 거절해야 할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(78, '고맙거나 좋은 마음을 표현할 때 나는?', '고맙거나 좋은 마음을 표현할 때 나는?', '고맙거나 좋은 마음을 표현할 때 {나:은는}?', '고맙거나 좋은 마음을 표현할 때 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(79, '누가 나한테 툭 쏘아붙이면 나는?', '누가 나한테 툭 쏘아붙이면 나는?', '누가 {나:한테} 툭 쏘아붙이면 {나:은는}?', '누가 {나:한테} 툭 쏘아붙이면 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp),
(80, '손해 볼 양보를 앞두고 나는?', '손해 볼 양보를 앞두고 나는?', '손해 볼 양보를 앞두고 {나:은는}?', '손해 볼 양보를 앞두고 {나:은는}?', 'SITUATION_5_CHOICE', 'AGREEABLENESS', true, current_timestamp, current_timestamp);

insert into answer_options (question_id, content_self, content_peer, sequence, active, created_at, updated_at) values
(1, '안 가. 계획없는 여행은 어지럽다.', '안 가. 계획없는 여행은 어지럽다.', 1, true, current_timestamp, current_timestamp),
(1, '숙소랑 일정부터 짜오면 그때 생각해볼게.', '숙소랑 일정부터 짜오면 그때 생각해볼게.', 2, true, current_timestamp, current_timestamp),
(1, '갈까 말까… 나쁘지 않을지도..?', '갈까 말까… 나쁘지 않을지도..?', 3, true, current_timestamp, current_timestamp),
(1, '너 가면 갈게ㅋㅋㅋ', '너 가면 갈게ㅋㅋㅋ', 4, true, current_timestamp, current_timestamp),
(1, '어디로 갈까?', '어디로 갈까?', 5, true, current_timestamp, current_timestamp),
(2, '화난다. 딱밤 마렵다.', '화난다. 딱밤 마렵다.', 1, true, current_timestamp, current_timestamp),
(2, '어… 그럼 이제 뭐 어떡하지.. 당황스럽다.', '어… 그럼 이제 뭐 어떡하지.. 당황스럽다.', 2, true, current_timestamp, current_timestamp),
(2, '뭐 그럴 수도 있지, 그러려니한다.', '뭐 그럴 수도 있지, 그러려니한다.', 3, true, current_timestamp, current_timestamp),
(2, '오히려 잘됐다 싶다.', '오히려 잘됐다 싶다.', 4, true, current_timestamp, current_timestamp),
(2, '이벤트 발생ㅋㅋ 나는야 럭키가이', '이벤트 발생ㅋㅋ 나는야 럭키가이', 5, true, current_timestamp, current_timestamp),
(3, '굳이? 잘 쓰던 거 두고 바꿀 필요를 못느낀다.', '굳이? 잘 쓰던 거 두고 바꿀 필요를 못느낀다.', 1, true, current_timestamp, current_timestamp),
(3, '유행 다 지나고 잠잠해지면 그때 써본다.', '유행 다 지나고 잠잠해지면 그때 써본다.', 2, true, current_timestamp, current_timestamp),
(3, '주변에서 다들 쓰면 슬그머니 따라한다.', '주변에서 다들 쓰면 슬그머니 따라한다.', 3, true, current_timestamp, current_timestamp),
(3, '관심 생기면 바로 깔아서 만져본다.', '관심 생기면 바로 깔아서 만져본다.', 4, true, current_timestamp, current_timestamp),
(3, '출시 알림 켜두고 누구보다 먼저 들어간다.', '출시 알림 켜두고 누구보다 먼저 들어간다.', 5, true, current_timestamp, current_timestamp),
(4, '한 장르만 깊게 판다. 덕후 그 자체', '한 장르만 깊게 판다. 덕후 그 자체', 1, true, current_timestamp, current_timestamp),
(4, '거의 한쪽으로 쏠려 있다.', '거의 한쪽으로 쏠려 있다.', 2, true, current_timestamp, current_timestamp),
(4, '두세 장르 왔다 갔다.', '두세 장르 왔다 갔다.', 3, true, current_timestamp, current_timestamp),
(4, '이것저것 폭넓게 본다.', '이것저것 폭넓게 본다.', 4, true, current_timestamp, current_timestamp),
(4, '그냥 보자고 하는거 본다.', '그냥 보자고 하는거 본다.', 5, true, current_timestamp, current_timestamp),
(5, '두렵고 최대한 피하고 싶다.', '두렵고 최대한 피하고 싶다.', 1, true, current_timestamp, current_timestamp),
(5, '잘될까 걱정부터 앞선다.', '잘될까 걱정부터 앞선다.', 2, true, current_timestamp, current_timestamp),
(5, '닥치면 어떻게든 되겠지 싶다.', '닥치면 어떻게든 되겠지 싶다.', 3, true, current_timestamp, current_timestamp),
(5, '새 출발 기대된다.', '새 출발 기대된다.', 4, true, current_timestamp, current_timestamp),
(5, '설레서 빨리 짐 싸고 싶다.', '설레서 빨리 짐 싸고 싶다.', 5, true, current_timestamp, current_timestamp),
(6, '됐어요, 정중히 사양한다.', '됐어요, 정중히 사양한다.', 1, true, current_timestamp, current_timestamp),
(6, '음… 하다가 결국 망설인다.', '음… 하다가 결국 망설인다.', 2, true, current_timestamp, current_timestamp),
(6, '분위기 봐서 휩쓸리면 한다.', '분위기 봐서 휩쓸리면 한다.', 3, true, current_timestamp, current_timestamp),
(6, '일단 한번 해보자.', '일단 한번 해보자.', 4, true, current_timestamp, current_timestamp),
(6, '“저요!” 하고 제일 먼저 손 든다.', '“저요!” 하고 제일 먼저 손 든다.', 5, true, current_timestamp, current_timestamp),
(7, '검증된 길만, 헤매는 거 질색이다.', '검증된 길만, 헤매는 거 질색이다.', 1, true, current_timestamp, current_timestamp),
(7, '웬만하면 아는 길로 간다.', '웬만하면 아는 길로 간다.', 2, true, current_timestamp, current_timestamp),
(7, '그날 상황 따라 다르다.', '그날 상황 따라 다르다.', 3, true, current_timestamp, current_timestamp),
(7, '새 길 궁금해서 자꾸 눈길 간다.', '새 길 궁금해서 자꾸 눈길 간다.', 4, true, current_timestamp, current_timestamp),
(7, '일부러 안 가본 길로 돌아간다.', '일부러 안 가본 길로 돌아간다.', 5, true, current_timestamp, current_timestamp),
(8, '말 걸까봐 무서워 시선 회피한다.', '말 걸까봐 무서워 시선 회피한다.', 1, true, current_timestamp, current_timestamp),
(8, '그냥 최대한 구석진 곳으로 간다.', '그냥 최대한 구석진 곳으로 간다.', 2, true, current_timestamp, current_timestamp),
(8, '무던하게 이야기 주고받는다.', '무던하게 이야기 주고받는다.', 3, true, current_timestamp, current_timestamp),
(8, '새 사람들이 궁금해 호기심 발동한다.', '새 사람들이 궁금해 호기심 발동한다.', 4, true, current_timestamp, current_timestamp),
(8, '오늘 이 자리에 있는 사람들이랑 짱친 먹고 간다.', '오늘 이 자리에 있는 사람들이랑 짱친 먹고 간다.', 5, true, current_timestamp, current_timestamp),
(9, '절대 안 먹는다. 입에 안 맞을 게 뻔하다.', '절대 안 먹는다. 입에 안 맞을 게 뻔하다.', 1, true, current_timestamp, current_timestamp),
(9, '냄새부터 꺼림칙하다.', '냄새부터 꺼림칙하다.', 2, true, current_timestamp, current_timestamp),
(9, '권하면 한 입 정도 먹어본다.', '권하면 한 입 정도 먹어본다.', 3, true, current_timestamp, current_timestamp),
(9, '흥미롭게 일단 시도해본다.', '흥미롭게 일단 시도해본다.', 4, true, current_timestamp, current_timestamp),
(9, '일부러 제일 생소한 걸 찾아 먹는다.', '일부러 제일 생소한 걸 찾아 먹는다.', 5, true, current_timestamp, current_timestamp),
(10, '일단 “왜 이래야 하지?”부터 따지고 본다.', '일단 “왜 이래야 하지?”부터 따지고 본다.', 1, true, current_timestamp, current_timestamp),
(10, '종종 “이거 꼭 이래야 해?” 의문 제기한다.', '종종 “이거 꼭 이래야 해?” 의문 제기한다.', 2, true, current_timestamp, current_timestamp),
(10, '상황 봐서 적당히한다.', '상황 봐서 적당히한다.', 3, true, current_timestamp, current_timestamp),
(10, '대체로 따르는 편이다.', '대체로 따르는 편이다.', 4, true, current_timestamp, current_timestamp),
(10, '군말 없이 정해진 대로 잘 지킨다.', '군말 없이 정해진 대로 잘 지킨다.', 5, true, current_timestamp, current_timestamp),
(11, '그게 제일 마음 편하고 안전하다.', '그게 제일 마음 편하고 안전하다.', 1, true, current_timestamp, current_timestamp),
(11, '웬만하면 다수를 따라간다.', '웬만하면 다수를 따라간다.', 2, true, current_timestamp, current_timestamp),
(11, '반반, 그때그때마다 다르다.', '반반, 그때그때마다 다르다.', 3, true, current_timestamp, current_timestamp),
(11, '내 방식 따로 찾는 편이다.', '내 방식 따로 찾는 편이다.', 4, true, current_timestamp, current_timestamp),
(11, '남들과 다른 길 가는 게 오히려 재밌다.', '남들과 다른 길 가는 게 오히려 재밌다.', 5, true, current_timestamp, current_timestamp),
(12, '익숙하게 하던 것만 하고 싶다.', '익숙하게 하던 것만 하고 싶다.', 1, true, current_timestamp, current_timestamp),
(12, '안전이 보장돼야 받는다.', '안전이 보장돼야 받는다.', 2, true, current_timestamp, current_timestamp),
(12, '받을까 말까 한참 고민한다.', '받을까 말까 한참 고민한다.', 3, true, current_timestamp, current_timestamp),
(12, '흥미가 생기면 받는다.', '흥미가 생기면 받는다.', 4, true, current_timestamp, current_timestamp),
(12, '생소해도 일단 부딪쳐보자.', '생소해도 일단 부딪쳐보자.', 5, true, current_timestamp, current_timestamp),
(13, '그런 거 없음, 생각도 안 해봤다.', '그런 거 없음, 생각도 안 해봤다.', 1, true, current_timestamp, current_timestamp),
(13, '머릿속에 막연하게만 몇개 있다.', '머릿속에 막연하게만 몇개 있다.', 2, true, current_timestamp, current_timestamp),
(13, '몇 개정도 적어뒀다.', '몇 개정도 적어뒀다.', 3, true, current_timestamp, current_timestamp),
(13, '리스트 만들어두고 가끔 실행한다.', '리스트 만들어두고 가끔 실행한다.', 4, true, current_timestamp, current_timestamp),
(13, '길고, 비울 새 없이 계속 채워나간다.', '길고, 비울 새 없이 계속 채워나간다.', 5, true, current_timestamp, current_timestamp),
(14, '봤던 거 또 보고 들었던 거 또 감상한다.', '봤던 거 또 보고 들었던 거 또 감상한다.', 1, true, current_timestamp, current_timestamp),
(14, '익숙한 것 위주로 감상한다.', '익숙한 것 위주로 감상한다.', 2, true, current_timestamp, current_timestamp),
(14, '평 무난한 추천작 하나 감상한다.', '평 무난한 추천작 하나 감상한다.', 3, true, current_timestamp, current_timestamp),
(14, '평 좋으면 새 거 도전해본다.', '평 좋으면 새 거 도전해본다.', 4, true, current_timestamp, current_timestamp),
(14, '아예 안 본 장르부터 찾아 나선다.', '아예 안 본 장르부터 찾아 나선다.', 5, true, current_timestamp, current_timestamp),
(15, '그냥 약속 장소 가서 핸드폰 본다.', '그냥 약속 장소 가서 핸드폰 본다.', 1, true, current_timestamp, current_timestamp),
(15, '약속 장소 가서 주위 잠깐 둘러본다.', '약속 장소 가서 주위 잠깐 둘러본다.', 2, true, current_timestamp, current_timestamp),
(15, '가기전 근처 벤치에 앉아 둘러본다.', '가기전 근처 벤치에 앉아 둘러본다.', 3, true, current_timestamp, current_timestamp),
(15, '안 가본 골목 한번 기웃거린다.', '안 가본 골목 한번 기웃거린다.', 4, true, current_timestamp, current_timestamp),
(15, '발길 닿는 대로 동네 한 바퀴 돌아본다.', '발길 닿는 대로 동네 한 바퀴 돌아본다.', 5, true, current_timestamp, current_timestamp),
(16, '무조건 하나만 정해 죽 파본다.', '무조건 하나만 정해 죽 파본다.', 1, true, current_timestamp, current_timestamp),
(16, '익숙한 분야 딱 하나 정한다.', '익숙한 분야 딱 하나 정한다.', 2, true, current_timestamp, current_timestamp),
(16, '두어 개 적당히 걸쳐본다.', '두어 개 적당히 걸쳐본다.', 3, true, current_timestamp, current_timestamp),
(16, '결 완전 다른 거 여러 개 기웃거린다.', '결 완전 다른 거 여러 개 기웃거린다.', 4, true, current_timestamp, current_timestamp),
(16, '안 겹치는 분야로 잔뜩 발 담금다.', '안 겹치는 분야로 잔뜩 발 담금다.', 5, true, current_timestamp, current_timestamp),
(17, '분 단위 일정표부터 완성한다.', '분 단위 일정표부터 완성한다.', 1, true, current_timestamp, current_timestamp),
(17, '동선이랑 숙소는 다 정해놔야 안심이다.', '동선이랑 숙소는 다 정해놔야 안심이다.', 2, true, current_timestamp, current_timestamp),
(17, '큰 틀만 잡고 나머진 현지에서 정한다.', '큰 틀만 잡고 나머진 현지에서 정한다.', 3, true, current_timestamp, current_timestamp),
(17, '표만 끊고 나머진 가서 본다.', '표만 끊고 나머진 가서 본다.', 4, true, current_timestamp, current_timestamp),
(17, '일단 출발, 잘 곳은 도착해서 찾아본다.', '일단 출발, 잘 곳은 도착해서 찾아본다.', 5, true, current_timestamp, current_timestamp),
(18, '집에서 이불과 한 몸이 되어 푹 쉰다.', '집에서 이불과 한 몸이 되어 푹 쉰다.', 1, true, current_timestamp, current_timestamp),
(18, '늘 가던 카페에서 시간 보낸다.', '늘 가던 카페에서 시간 보낸다.', 2, true, current_timestamp, current_timestamp),
(18, '가까운 데 산책 정도 하러간다.', '가까운 데 산책 정도 하러간다.', 3, true, current_timestamp, current_timestamp),
(18, '안 해본 원데이 클래스 신청해본다.', '안 해본 원데이 클래스 신청해본다.', 4, true, current_timestamp, current_timestamp),
(18, '처음 가보는 동네로 무작정 탐방한다.', '처음 가보는 동네로 무작정 탐방한다.', 5, true, current_timestamp, current_timestamp),
(19, '나랑은 상관없는 남의 얘기다.', '나랑은 상관없는 남의 얘기다.', 1, true, current_timestamp, current_timestamp),
(19, '유행 다 지나면 슬쩍 발 담가본다.', '유행 다 지나면 슬쩍 발 담가본다.', 2, true, current_timestamp, current_timestamp),
(19, '남들 하는 거 보고 정한다.', '남들 하는 거 보고 정한다.', 3, true, current_timestamp, current_timestamp),
(19, '관심 갖고 흐름을 지켜본다.', '관심 갖고 흐름을 지켜본다.', 4, true, current_timestamp, current_timestamp),
(19, '누구보다 먼저 뛰어든다.', '누구보다 먼저 뛰어든다.', 5, true, current_timestamp, current_timestamp),
(20, '안정적이라 오히려 좋다.', '안정적이라 오히려 좋다.', 1, true, current_timestamp, current_timestamp),
(20, '별 불만 없이 그냥 지낸다.', '별 불만 없이 그냥 지낸다.', 2, true, current_timestamp, current_timestamp),
(20, '가끔 답답하긴 하다.', '가끔 답답하긴 하다.', 3, true, current_timestamp, current_timestamp),
(20, '종종 작은 변화를 주려 한다.', '종종 작은 변화를 주려 한다.', 4, true, current_timestamp, current_timestamp),
(20, '못 견디고 자꾸 새 걸 벌인다.', '못 견디고 자꾸 새 걸 벌인다.', 5, true, current_timestamp, current_timestamp),
(21, '끝까지 미루다 결국 안 한다.', '끝까지 미루다 결국 안 한다.', 1, true, current_timestamp, current_timestamp),
(21, '마감 코앞에 닥쳐서야 시작한다.', '마감 코앞에 닥쳐서야 시작한다.', 2, true, current_timestamp, current_timestamp),
(21, '적당한 때가 오면 한다.', '적당한 때가 오면 한다.', 3, true, current_timestamp, current_timestamp),
(21, '미리미리 해둔다.', '미리미리 해둔다.', 4, true, current_timestamp, current_timestamp),
(21, '받자마자 그 자리에서 끝낸다.', '받자마자 그 자리에서 끝낸다.', 5, true, current_timestamp, current_timestamp),
(22, '혼돈의 카오스 그 자체..', '혼돈의 카오스 그 자체..', 1, true, current_timestamp, current_timestamp),
(22, '늘 좀 어수선하다.', '늘 좀 어수선하다.', 2, true, current_timestamp, current_timestamp),
(22, '그냥 적당히 평범하게 있는 수준이다.', '그냥 적당히 평범하게 있는 수준이다.', 3, true, current_timestamp, current_timestamp),
(22, '대체로 깔끔하게 정리 된 편이다.', '대체로 깔끔하게 정리 된 편이다.', 4, true, current_timestamp, current_timestamp),
(22, '자로 잰 듯 각이 잡혀 있다.', '자로 잰 듯 각이 잡혀 있다.', 5, true, current_timestamp, current_timestamp),
(23, '생각 없이 일단 손부터 댄다.', '생각 없이 일단 손부터 댄다.', 1, true, current_timestamp, current_timestamp),
(23, '별 계획 없이 그냥 시작한다.', '별 계획 없이 그냥 시작한다.', 2, true, current_timestamp, current_timestamp),
(23, '머릿속으로 대충 순서를 그린다.', '머릿속으로 대충 순서를 그린다.', 3, true, current_timestamp, current_timestamp),
(23, '큰 틀부터 잡고 들어간다.', '큰 틀부터 잡고 들어간다.', 4, true, current_timestamp, current_timestamp),
(23, '순서에 기한까지 다 정해놓고 시작한다.', '순서에 기한까지 다 정해놓고 시작한다.', 5, true, current_timestamp, current_timestamp),
(24, '어느새 흐지부지 사라진다.', '어느새 흐지부지 사라진다.', 1, true, current_timestamp, current_timestamp),
(24, '대충 마무리하고 손 뗀다.', '대충 마무리하고 손 뗀다.', 2, true, current_timestamp, current_timestamp),
(24, '그럭저럭 끝까지는 간다.', '그럭저럭 끝까지는 간다.', 3, true, current_timestamp, current_timestamp),
(24, '빠진 데 없이 꼼꼼히 끝낸다.', '빠진 데 없이 꼼꼼히 끝낸다.', 4, true, current_timestamp, current_timestamp),
(24, '마음에 들 때까지 끝까지 다듬는다.', '마음에 들 때까지 끝까지 다듬는다.', 5, true, current_timestamp, current_timestamp),
(25, '늘 늦어서 헐레벌떡 뛰어온다.', '늘 늦어서 헐레벌떡 뛰어온다.', 1, true, current_timestamp, current_timestamp),
(25, '종종 아슬아슬하게 도착한다.', '종종 아슬아슬하게 도착한다.', 2, true, current_timestamp, current_timestamp),
(25, '보통 제시간에 맞춰 온다.', '보통 제시간에 맞춰 온다.', 3, true, current_timestamp, current_timestamp),
(25, '살짝 일찍 와서 기다린다.', '살짝 일찍 와서 기다린다.', 4, true, current_timestamp, current_timestamp),
(25, '항상 먼저 와 자리 잡고 있다.', '항상 먼저 와 자리 잡고 있다.', 5, true, current_timestamp, current_timestamp),
(26, '결국 못 내고 만다.', '결국 못 내고 만다.', 1, true, current_timestamp, current_timestamp),
(26, '밤새 벼락치기로 아슬하게 세이프.', '밤새 벼락치기로 아슬하게 세이프.', 2, true, current_timestamp, current_timestamp),
(26, '적당히 일정 잡아두고 시간 맞춰 제출한다.', '적당히 일정 잡아두고 시간 맞춰 제출한다.', 3, true, current_timestamp, current_timestamp),
(26, '여유 있게 끝내놓는다.', '여유 있게 끝내놓는다.', 4, true, current_timestamp, current_timestamp),
(26, '진작 끝내놓고 느긋하게 커피 마신다.', '진작 끝내놓고 느긋하게 커피 마신다.', 5, true, current_timestamp, current_timestamp),
(27, '큰 그림만 보고 세부는 통째로 넘긴다.', '큰 그림만 보고 세부는 통째로 넘긴다.', 1, true, current_timestamp, current_timestamp),
(27, '자잘한 건 자주 놓친다.', '자잘한 건 자주 놓친다.', 2, true, current_timestamp, current_timestamp),
(27, '보통은 챙긴다.', '보통은 챙긴다.', 3, true, current_timestamp, current_timestamp),
(27, '세세한 것도 꽤 본다.', '세세한 것도 꽤 본다.', 4, true, current_timestamp, current_timestamp),
(27, '작은 오타 하나까지 다 잡아낸다.', '작은 오타 하나까지 다 잡아낸다.', 5, true, current_timestamp, current_timestamp),
(28, '머리로만 외우다 자주 까먹는다.', '머리로만 외우다 자주 까먹는다.', 1, true, current_timestamp, current_timestamp),
(28, '가끔 생각나면 메모한다.', '가끔 생각나면 메모한다.', 2, true, current_timestamp, current_timestamp),
(28, '중요한 것만 적어둔다.', '중요한 것만 적어둔다.', 3, true, current_timestamp, current_timestamp),
(28, '캘린더에 깔끔하게 정리한다.', '캘린더에 깔끔하게 정리한다.', 4, true, current_timestamp, current_timestamp),
(28, '캘린더에 알림까지 세팅해둔다.', '캘린더에 알림까지 세팅해둔다.', 5, true, current_timestamp, current_timestamp),
(29, '알면서도 그냥 둔다.', '알면서도 그냥 둔다.', 1, true, current_timestamp, current_timestamp),
(29, '“다음에 고치지 뭐” 하고 넘긴다.', '“다음에 고치지 뭐” 하고 넘긴다.', 2, true, current_timestamp, current_timestamp),
(29, '눈에 띄면 고친다.', '눈에 띄면 고친다.', 3, true, current_timestamp, current_timestamp),
(29, '발견하는 즉시 수정한다', '발견하는 즉시 수정한다', 4, true, current_timestamp, current_timestamp),
(29, '왜 그랬는지 원인까지 파서 고친다', '왜 그랬는지 원인까지 파서 고친다', 5, true, current_timestamp, current_timestamp),
(30, '완전 무계획으로 산다', '완전 무계획으로 산다', 1, true, current_timestamp, current_timestamp),
(30, '통장 잔고만 가끔 확인한다', '통장 잔고만 가끔 확인한다', 2, true, current_timestamp, current_timestamp),
(30, '대충 머릿속으로 관리한다', '대충 머릿속으로 관리한다', 3, true, current_timestamp, current_timestamp),
(30, '예산을 잡아두고 쓴다', '예산을 잡아두고 쓴다', 4, true, current_timestamp, current_timestamp),
(30, '예산에 가계부 기록까지 철저하다', '예산에 가계부 기록까지 철저하다', 5, true, current_timestamp, current_timestamp),
(31, '별로 신경 안 쓰고 잘 안 지킨다', '별로 신경 안 쓰고 잘 안 지킨다', 1, true, current_timestamp, current_timestamp),
(31, '“유연하게” 하다 자주 어긴다', '“유연하게” 하다 자주 어긴다', 2, true, current_timestamp, current_timestamp),
(31, '웬만하면 지킨다', '웬만하면 지킨다', 3, true, current_timestamp, current_timestamp),
(31, '잘 지키는 편이다', '잘 지키는 편이다', 4, true, current_timestamp, current_timestamp),
(31, '철저하게 지킨다', '철저하게 지킨다', 5, true, current_timestamp, current_timestamp),
(32, '계속 미루다 안 한다', '계속 미루다 안 한다', 1, true, current_timestamp, current_timestamp),
(32, '한계가 오면 몰아서 한다', '한계가 오면 몰아서 한다', 2, true, current_timestamp, current_timestamp),
(32, '생각나면 한 번씩 한다', '생각나면 한 번씩 한다', 3, true, current_timestamp, current_timestamp),
(32, '그때그때 바로바로 한다', '그때그때 바로바로 한다', 4, true, current_timestamp, current_timestamp),
(32, '습관처럼 늘 정돈해둔다', '습관처럼 늘 정돈해둔다', 5, true, current_timestamp, current_timestamp),
(33, '뭐부터 해야 할지 모른다', '뭐부터 해야 할지 모른다', 1, true, current_timestamp, current_timestamp),
(33, '자주 우왕좌왕한다', '자주 우왕좌왕한다', 2, true, current_timestamp, current_timestamp),
(33, '보통은 가린다', '보통은 가린다', 3, true, current_timestamp, current_timestamp),
(33, '중요한 것부터 잘 가린다', '중요한 것부터 잘 가린다', 4, true, current_timestamp, current_timestamp),
(33, '뭐부터 할지 명확하게 정한다', '뭐부터 할지 명확하게 정한다', 5, true, current_timestamp, current_timestamp),
(34, '출발 직전에 대충 욱여넣는다', '출발 직전에 대충 욱여넣는다', 1, true, current_timestamp, current_timestamp),
(34, '빠뜨리는 게 꼭 있다', '빠뜨리는 게 꼭 있다', 2, true, current_timestamp, current_timestamp),
(34, '보통 수준으로 챙긴다', '보통 수준으로 챙긴다', 3, true, current_timestamp, current_timestamp),
(34, '리스트 보면서 챙긴다', '리스트 보면서 챙긴다', 4, true, current_timestamp, current_timestamp),
(34, '며칠 전부터 완벽하게 세팅해둔다', '며칠 전부터 완벽하게 세팅해둔다', 5, true, current_timestamp, current_timestamp),
(35, '귀찮아서 다 건너뛴다', '귀찮아서 다 건너뛴다', 1, true, current_timestamp, current_timestamp),
(35, '자주 생략한다', '자주 생략한다', 2, true, current_timestamp, current_timestamp),
(35, '중요한 것만 따른다', '중요한 것만 따른다', 3, true, current_timestamp, current_timestamp),
(35, '잘 따르는 편이다', '잘 따르는 편이다', 4, true, current_timestamp, current_timestamp),
(35, '차근차근 빠짐없이 따른다', '차근차근 빠짐없이 따른다', 5, true, current_timestamp, current_timestamp),
(36, '3일 만에 끝난다', '3일 만에 끝난다', 1, true, current_timestamp, current_timestamp),
(36, '어느새 흐지부지된다', '어느새 흐지부지된다', 2, true, current_timestamp, current_timestamp),
(36, '했다 말다 들쭉날쭉', '했다 말다 들쭉날쭉', 3, true, current_timestamp, current_timestamp),
(36, '꽤 오래 간다', '꽤 오래 간다', 4, true, current_timestamp, current_timestamp),
(36, '아예 루틴으로 정착시킨다', '아예 루틴으로 정착시킨다', 5, true, current_timestamp, current_timestamp),
(37, '어디가 바닥인지 모를 정도다', '어디가 바닥인지 모를 정도다', 1, true, current_timestamp, current_timestamp),
(37, '늘 좀 어질러져 있다', '늘 좀 어질러져 있다', 2, true, current_timestamp, current_timestamp),
(37, '그냥 평범한 수준', '그냥 평범한 수준', 3, true, current_timestamp, current_timestamp),
(37, '대체로 깔끔한 편', '대체로 깔끔한 편', 4, true, current_timestamp, current_timestamp),
(37, '물건마다 제자리에 딱 놓여 있다', '물건마다 제자리에 딱 놓여 있다', 5, true, current_timestamp, current_timestamp),
(38, '일단 지르고 나중에 후회한다', '일단 지르고 나중에 후회한다', 1, true, current_timestamp, current_timestamp),
(38, '충동적으로 결정하는 편이다', '충동적으로 결정하는 편이다', 2, true, current_timestamp, current_timestamp),
(38, '그때그때 다르다', '그때그때 다르다', 3, true, current_timestamp, current_timestamp),
(38, '며칠 생각해보고 정한다', '며칠 생각해보고 정한다', 4, true, current_timestamp, current_timestamp),
(38, '따질 거 다 따지고 신중하게 결정한다', '따질 거 다 따지고 신중하게 결정한다', 5, true, current_timestamp, current_timestamp),
(39, '마음만 먹고 흐지부지된다', '마음만 먹고 흐지부지된다', 1, true, current_timestamp, current_timestamp),
(39, '결심만 하고 끝', '결심만 하고 끝', 2, true, current_timestamp, current_timestamp),
(39, '일단 시작은 해본다', '일단 시작은 해본다', 3, true, current_timestamp, current_timestamp),
(39, '계획을 제대로 세운다', '계획을 제대로 세운다', 4, true, current_timestamp, current_timestamp),
(39, '계획에 실행에 점검까지 다 한다', '계획에 실행에 점검까지 다 한다', 5, true, current_timestamp, current_timestamp),
(40, '뭐가 어디 있는지 본인도 모른다', '뭐가 어디 있는지 본인도 모른다', 1, true, current_timestamp, current_timestamp),
(40, '어수선한데 그냥 둔다', '어수선한데 그냥 둔다', 2, true, current_timestamp, current_timestamp),
(40, '가끔 마음먹고 한 번 정리한다', '가끔 마음먹고 한 번 정리한다', 3, true, current_timestamp, current_timestamp),
(40, '웬만하면 정돈된 편', '웬만하면 정돈된 편', 4, true, current_timestamp, current_timestamp),
(40, '늘 칼같이 정리돼 있다', '늘 칼같이 정리돼 있다', 5, true, current_timestamp, current_timestamp),
(41, '구석에 앉아 핸드폰 배터리만 닳는 중', '구석에 앉아 핸드폰 배터리만 닳는 중', 1, true, current_timestamp, current_timestamp),
(41, '옆사람에게 화장실 정도 물어봄', '옆사람에게 화장실 정도 물어봄', 2, true, current_timestamp, current_timestamp),
(41, '누가 말 걸어주면 받아주는 정도', '누가 말 걸어주면 받아주는 정도', 3, true, current_timestamp, current_timestamp),
(41, '어느새 서너 명과 인스타 교환 중', '어느새 서너 명과 인스타 교환 중', 4, true, current_timestamp, current_timestamp),
(41, '30분 만에 단톡방 만들자고 함', '30분 만에 단톡방 만들자고 함', 5, true, current_timestamp, current_timestamp),
(42, '침대 밖으로 나오지 않음', '침대 밖으로 나오지 않음', 1, true, current_timestamp, current_timestamp),
(42, '집에서 뒹굴며 휴식', '집에서 뒹굴며 휴식', 2, true, current_timestamp, current_timestamp),
(42, '친구랑 전화하거나 취미 생활 즐김', '친구랑 전화하거나 취미 생활 즐김', 3, true, current_timestamp, current_timestamp),
(42, '친구 한두 명 불러서 가볍게 수다', '친구 한두 명 불러서 가볍게 수다', 4, true, current_timestamp, current_timestamp),
(42, '사람들 속에 파묻혀야 비로소 살아남', '사람들 속에 파묻혀야 비로소 살아남', 5, true, current_timestamp, current_timestamp),
(43, '갑자기 신발끈 묶으며 눈 피함', '갑자기 신발끈 묶으며 눈 피함', 1, true, current_timestamp, current_timestamp),
(43, '결국 떠밀려서 함', '결국 떠밀려서 함', 2, true, current_timestamp, current_timestamp),
(43, '콕 집어 시키면 그냥 함', '콕 집어 시키면 그냥 함', 3, true, current_timestamp, current_timestamp),
(43, '시키면 곧잘 해냄', '시키면 곧잘 해냄', 4, true, current_timestamp, current_timestamp),
(43, '손부터 번쩍 들고 즐김', '손부터 번쩍 들고 즐김', 5, true, current_timestamp, current_timestamp),
(44, '머릿속이 갑자기 백지장', '머릿속이 갑자기 백지장', 1, true, current_timestamp, current_timestamp),
(44, '손에 땀나고 목소리 떨림', '손에 땀나고 목소리 떨림', 2, true, current_timestamp, current_timestamp),
(44, '떨리지만 덤덤하게 말함', '떨리지만 덤덤하게 말함', 3, true, current_timestamp, current_timestamp),
(44, '의외로 괜찮음', '의외로 괜찮음', 4, true, current_timestamp, current_timestamp),
(44, '오히려 심장이 신나서 뜀', '오히려 심장이 신나서 뜀', 5, true, current_timestamp, current_timestamp),
(45, '부담돼서 정중히 패스', '부담돼서 정중히 패스', 1, true, current_timestamp, current_timestamp),
(45, '웬만하면 안 감', '웬만하면 안 감', 2, true, current_timestamp, current_timestamp),
(45, '친한 사람 같이 가면 감', '친한 사람 같이 가면 감', 3, true, current_timestamp, current_timestamp),
(45, '어지간하면 감', '어지간하면 감', 4, true, current_timestamp, current_timestamp),
(45, '일정부터 비워두고 무조건 감', '일정부터 비워두고 무조건 감', 5, true, current_timestamp, current_timestamp),
(46, '최대한 짧게 끊고 싶음', '최대한 짧게 끊고 싶음', 1, true, current_timestamp, current_timestamp),
(46, '네/아니오 단답 위주', '네/아니오 단답 위주', 2, true, current_timestamp, current_timestamp),
(46, '적당히 오감', '적당히 오감', 3, true, current_timestamp, current_timestamp),
(46, '이런저런 얘기로 길게 이어감', '이런저런 얘기로 길게 이어감', 4, true, current_timestamp, current_timestamp),
(46, '끊을 틈 없이 수다 폭발', '끊을 틈 없이 수다 폭발', 5, true, current_timestamp, current_timestamp),
(47, '끝까지 탬버린 담당', '끝까지 탬버린 담당', 1, true, current_timestamp, current_timestamp),
(47, '떠밀려서 마지못해 한곡 부름', '떠밀려서 마지못해 한곡 부름', 2, true, current_timestamp, current_timestamp),
(47, '분위기 보면서 몇곡 부름', '분위기 보면서 몇곡 부름', 3, true, current_timestamp, current_timestamp),
(47, '곧잘 나서서 재밌게 부름', '곧잘 나서서 재밌게 부름', 4, true, current_timestamp, current_timestamp),
(47, '제일 먼저 마이크 잡고 무대를 압도함', '제일 먼저 마이크 잡고 무대를 압도함', 5, true, current_timestamp, current_timestamp),
(48, '차라리 헤매고 말지, 절대 못 함', '차라리 헤매고 말지, 절대 못 함', 1, true, current_timestamp, current_timestamp),
(48, '부담스러워 망설임', '부담스러워 망설임', 2, true, current_timestamp, current_timestamp),
(48, '꼭 필요하면 함', '꼭 필요하면 함', 3, true, current_timestamp, current_timestamp),
(48, '별 거리낌 없이 그냥 물어봄', '별 거리낌 없이 그냥 물어봄', 4, true, current_timestamp, current_timestamp),
(48, '오히려 말 거는 걸 즐김', '오히려 말 거는 걸 즐김', 5, true, current_timestamp, current_timestamp),
(49, '늘 잔잔하고 차분', '늘 잔잔하고 차분', 1, true, current_timestamp, current_timestamp),
(49, '조용한 편', '조용한 편', 2, true, current_timestamp, current_timestamp),
(49, '적당히 말하고 적당히 조용함', '적당히 말하고 적당히 조용함', 3, true, current_timestamp, current_timestamp),
(49, '활발한 편', '활발한 편', 4, true, current_timestamp, current_timestamp),
(49, '어딜 가나 에너지 만렙', '어딜 가나 에너지 만렙', 5, true, current_timestamp, current_timestamp),
(50, '무조건 조용한 카페', '무조건 조용한 카페', 1, true, current_timestamp, current_timestamp),
(50, '조용한 쪽 선호', '조용한 쪽 선호', 2, true, current_timestamp, current_timestamp),
(50, '그날 기분 따라', '그날 기분 따라', 3, true, current_timestamp, current_timestamp),
(50, '북적이는 쪽 선호', '북적이는 쪽 선호', 4, true, current_timestamp, current_timestamp),
(50, '사람 많을수록 더 신남', '사람 많을수록 더 신남', 5, true, current_timestamp, current_timestamp),
(51, '낯가림이 눈에 보임', '낯가림이 눈에 보임', 1, true, current_timestamp, current_timestamp),
(51, '조용하고 차분', '조용하고 차분', 2, true, current_timestamp, current_timestamp),
(51, '무난한 편', '무난한 편', 3, true, current_timestamp, current_timestamp),
(51, '싹싹하고 붙임성 있음', '싹싹하고 붙임성 있음', 4, true, current_timestamp, current_timestamp),
(51, '처음 본 사이인데 원래 알던 느낌', '처음 본 사이인데 원래 알던 느낌', 5, true, current_timestamp, current_timestamp),
(52, '여전히 서먹한 사이', '여전히 서먹한 사이', 1, true, current_timestamp, current_timestamp),
(52, '인사 정도 트인 사이', '인사 정도 트인 사이', 2, true, current_timestamp, current_timestamp),
(52, '그럭저럭 대화는 됨', '그럭저럭 대화는 됨', 3, true, current_timestamp, current_timestamp),
(52, '꽤 편하게 얘기하는 사이', '꽤 편하게 얘기하는 사이', 4, true, current_timestamp, current_timestamp),
(52, '원래 알던 사이처럼 친해짐', '원래 알던 사이처럼 친해짐', 5, true, current_timestamp, current_timestamp),
(53, '상대가 연락 올 때까지 기다림', '상대가 연락 올 때까지 기다림', 1, true, current_timestamp, current_timestamp),
(53, '어지간하면 먼저 안 함', '어지간하면 먼저 안 함', 2, true, current_timestamp, current_timestamp),
(53, '생각나면 가끔 연락', '생각나면 가끔 연락', 3, true, current_timestamp, current_timestamp),
(53, '먼저 연락 잘 돌림', '먼저 연락 잘 돌림', 4, true, current_timestamp, current_timestamp),
(53, '약속이고 모임이고 다 내가 잡음', '약속이고 모임이고 다 내가 잡음', 5, true, current_timestamp, current_timestamp),
(54, '떨려서 준비한 말을 까먹음', '떨려서 준비한 말을 까먹음', 1, true, current_timestamp, current_timestamp),
(54, '이름만 말하고 빛의 속도로 앉음', '이름만 말하고 빛의 속도로 앉음', 2, true, current_timestamp, current_timestamp),
(54, '무난하게 한두 마디 하고 마무리', '무난하게 한두 마디 하고 마무리', 3, true, current_timestamp, current_timestamp),
(54, '분위기 보며 농담 하나 슬쩍 곁들임', '분위기 보며 농담 하나 슬쩍 곁들임', 4, true, current_timestamp, current_timestamp),
(54, '능청스럽게 좌중을 웃기고 박수까지 받음', '능청스럽게 좌중을 웃기고 박수까지 받음', 5, true, current_timestamp, current_timestamp),
(55, '이쪽 보지 말아달라고 함.', '이쪽 보지 말아달라고 함.', 1, true, current_timestamp, current_timestamp),
(55, '어쩔 수 없이 받응은 함.', '어쩔 수 없이 받응은 함.', 2, true, current_timestamp, current_timestamp),
(55, '그럭저럭 해야할 이야기를 함', '그럭저럭 해야할 이야기를 함', 3, true, current_timestamp, current_timestamp),
(55, '은근히 즐기는 편', '은근히 즐기는 편', 4, true, current_timestamp, current_timestamp),
(55, '내가 이 모임의 슈퍼스타', '내가 이 모임의 슈퍼스타', 5, true, current_timestamp, current_timestamp),
(56, '눈도 안 마주치고 폰만 봄', '눈도 안 마주치고 폰만 봄', 1, true, current_timestamp, current_timestamp),
(56, '상대가 말 걸면 받아주는 정도', '상대가 말 걸면 받아주는 정도', 2, true, current_timestamp, current_timestamp),
(56, '분위기 보다 한마디', '분위기 보다 한마디', 3, true, current_timestamp, current_timestamp),
(56, '기회 되면 먼저 말 붙임', '기회 되면 먼저 말 붙임', 4, true, current_timestamp, current_timestamp),
(56, '망설임 없이 먼저 말 검', '망설임 없이 먼저 말 검', 5, true, current_timestamp, current_timestamp),
(57, '절대 다 못가 바로 잠수', '절대 다 못가 바로 잠수', 1, true, current_timestamp, current_timestamp),
(57, '생각만 해도 너무 힘듦지만 일단 감', '생각만 해도 너무 힘듦지만 일단 감', 2, true, current_timestamp, current_timestamp),
(57, '그럭저럭 다니긴 했지만 살짝 지침', '그럭저럭 다니긴 했지만 살짝 지침', 3, true, current_timestamp, current_timestamp),
(57, '무리없이 소화해님', '무리없이 소화해님', 4, true, current_timestamp, current_timestamp),
(57, '여러 사람 만날 생각에 설렘', '여러 사람 만날 생각에 설렘', 5, true, current_timestamp, current_timestamp),
(58, '슬그머니 일찍 빠짐', '슬그머니 일찍 빠짐', 1, true, current_timestamp, current_timestamp),
(58, '적당히 있다 감', '적당히 있다 감', 2, true, current_timestamp, current_timestamp),
(58, '끝날 때까지는 있음', '끝날 때까지는 있음', 3, true, current_timestamp, current_timestamp),
(58, '분위기 맞춰 끝까지 함께', '분위기 맞춰 끝까지 함께', 4, true, current_timestamp, current_timestamp),
(58, '“2차 가자!” 제일 신난 사람', '“2차 가자!” 제일 신난 사람', 5, true, current_timestamp, current_timestamp),
(59, '한 학기 정도는 같이 지내봐야 마음을 열음', '한 학기 정도는 같이 지내봐야 마음을 열음', 1, true, current_timestamp, current_timestamp),
(59, '몇 주는 꾸준히 봐야 정이감', '몇 주는 꾸준히 봐야 정이감', 2, true, current_timestamp, current_timestamp),
(59, '한 두번 만나니까 마음이 열림', '한 두번 만나니까 마음이 열림', 3, true, current_timestamp, current_timestamp),
(59, '일정이 끝나가면서 친하게 지내기로 함', '일정이 끝나가면서 친하게 지내기로 함', 4, true, current_timestamp, current_timestamp),
(59, '만난 그순간 바로 친구 등극', '만난 그순간 바로 친구 등극', 5, true, current_timestamp, current_timestamp),
(60, '읽고 답은 안 함', '읽고 답은 안 함', 1, true, current_timestamp, current_timestamp),
(60, '가끔 이모티콘만 톡', '가끔 이모티콘만 톡', 2, true, current_timestamp, current_timestamp),
(60, '대화에 맞장구 쳐줌', '대화에 맞장구 쳐줌', 3, true, current_timestamp, current_timestamp),
(60, '자주 끼어들어 떠듦', '자주 끼어들어 떠듦', 4, true, current_timestamp, current_timestamp),
(60, '거의 자기가 대화 끌고 감', '거의 자기가 대화 끌고 감', 5, true, current_timestamp, current_timestamp),
(61, '다음날 아침에 보고 “헐 무슨 일이었어”', '다음날 아침에 보고 “헐 무슨 일이었어”', 1, true, current_timestamp, current_timestamp),
(61, '“왜? 무슨 일?” 짧게 묻고 다시 잠', '“왜? 무슨 일?” 짧게 묻고 다시 잠', 2, true, current_timestamp, current_timestamp),
(61, '톡으로 이것 저것 들어줌', '톡으로 이것 저것 들어줌', 3, true, current_timestamp, current_timestamp),
(61, '바로 전화 걸어 끝까지 들어줌', '바로 전화 걸어 끝까지 들어줌', 4, true, current_timestamp, current_timestamp),
(61, '“지금 어디야” 하고 잠옷 바람으로 나옴', '“지금 어디야” 하고 잠옷 바람으로 나옴', 5, true, current_timestamp, current_timestamp),
(62, '“그건 좀 어렵겠다” 단칼에 거절', '“그건 좀 어렵겠다” 단칼에 거절', 1, true, current_timestamp, current_timestamp),
(62, '적당한 핑계 대고 슬쩍 뺌', '적당한 핑계 대고 슬쩍 뺌', 2, true, current_timestamp, current_timestamp),
(62, '그날 컨디션 봐서 결정', '그날 컨디션 봐서 결정', 3, true, current_timestamp, current_timestamp),
(62, '한숨 한 번 쉬고 웬만하면 들어줌', '한숨 한 번 쉬고 웬만하면 들어줌', 4, true, current_timestamp, current_timestamp),
(62, '“당연히 가야지” 하고 흔쾌히 나섬', '“당연히 가야지” 하고 흔쾌히 나섬', 5, true, current_timestamp, current_timestamp),
(63, '“이거 누가 이랬어?” 대놓고 따짐', '“이거 누가 이랬어?” 대놓고 따짐', 1, true, current_timestamp, current_timestamp),
(63, '“다음엔 좀 조심하자” 한소리 함', '“다음엔 좀 조심하자” 한소리 함', 2, true, current_timestamp, current_timestamp),
(63, '별말 없이 자기 할 일 함', '별말 없이 자기 할 일 함', 3, true, current_timestamp, current_timestamp),
(63, '“괜찮아 그럴 수 있어” 하고 다독임', '“괜찮아 그럴 수 있어” 하고 다독임', 4, true, current_timestamp, current_timestamp),
(63, '“내가 같이 해결할게” 하며 감싸고 도와줌', '“내가 같이 해결할게” 하며 감싸고 도와줌', 5, true, current_timestamp, current_timestamp),
(64, '직설적으로 솔직하게, 듣다 보면 따끔함', '직설적으로 솔직하게, 듣다 보면 따끔함', 1, true, current_timestamp, current_timestamp),
(64, '직설적으로 이야기는 하지만 필터링은 함', '직설적으로 이야기는 하지만 필터링은 함', 2, true, current_timestamp, current_timestamp),
(64, '그냥 무난하게 별 생각 없음', '그냥 무난하게 별 생각 없음', 3, true, current_timestamp, current_timestamp),
(64, '부드럽게 느껴짐', '부드럽게 느껴짐', 4, true, current_timestamp, current_timestamp),
(64, '어떤 말도 다정하게 들림', '어떤 말도 다정하게 들림', 5, true, current_timestamp, current_timestamp),
(65, '정면으로 붙어서 끝장 봄', '정면으로 붙어서 끝장 봄', 1, true, current_timestamp, current_timestamp),
(65, '어떻게든 안 지려고 버팀', '어떻게든 안 지려고 버팀', 2, true, current_timestamp, current_timestamp),
(65, '일단 상황 살핌', '일단 상황 살핌', 3, true, current_timestamp, current_timestamp),
(65, '“좋게 좋게 가자” 하며 원만히 풀려 함', '“좋게 좋게 가자” 하며 원만히 풀려 함', 4, true, current_timestamp, current_timestamp),
(65, '양쪽 다 어르고 달래서 기어이 화해시킴', '양쪽 다 어르고 달래서 기어이 화해시킴', 5, true, current_timestamp, current_timestamp),
(66, '일단 경계부터, 신경 곤두세우고 관찰함', '일단 경계부터, 신경 곤두세우고 관찰함', 1, true, current_timestamp, current_timestamp),
(66, '평범하게 대하지만 속으로 경계함', '평범하게 대하지만 속으로 경계함', 2, true, current_timestamp, current_timestamp),
(66, '그냥 평범하게 대함', '그냥 평범하게 대함', 3, true, current_timestamp, current_timestamp),
(66, '열린 태도로 먼저 다가감', '열린 태도로 먼저 다가감', 4, true, current_timestamp, current_timestamp),
(66, '일단 좋은 사람이라 믿고 보며 꼬리 흔듦', '일단 좋은 사람이라 믿고 보며 꼬리 흔듦', 5, true, current_timestamp, current_timestamp),
(67, '못 본 척 지나감', '못 본 척 지나감', 1, true, current_timestamp, current_timestamp),
(67, '봤지만 모른 척', '봤지만 모른 척', 2, true, current_timestamp, current_timestamp),
(67, '“도와줄까?” 물어보면 도움', '“도와줄까?” 물어보면 도움', 3, true, current_timestamp, current_timestamp),
(67, '먼저 다가가 한쪽을 들어줌', '먼저 다가가 한쪽을 들어줌', 4, true, current_timestamp, current_timestamp),
(67, '묻지도 않고 알아서 척척 도움', '묻지도 않고 알아서 척척 도움', 5, true, current_timestamp, current_timestamp),
(68, '가차 없이 팩트로 직격', '가차 없이 팩트로 직격', 1, true, current_timestamp, current_timestamp),
(68, '좀 날 서게 말함', '좀 날 서게 말함', 2, true, current_timestamp, current_timestamp),
(68, '사실대로 담담히', '사실대로 담담히', 3, true, current_timestamp, current_timestamp),
(68, '상대 입장 배려하며', '상대 입장 배려하며', 4, true, current_timestamp, current_timestamp),
(68, '상처 안 가게 한참을 고르고 골라 말함', '상처 안 가게 한참을 고르고 골라 말함', 5, true, current_timestamp, current_timestamp),
(69, '“안 돼” 단호하게 지르고 안들음.', '“안 돼” 단호하게 지르고 안들음.', 1, true, current_timestamp, current_timestamp),
(69, '적당히 둘러대고 거절', '적당히 둘러대고 거절', 2, true, current_timestamp, current_timestamp),
(69, '“이건 좀 어렵겠다” 좋게 타이름', '“이건 좀 어렵겠다” 좋게 타이름', 3, true, current_timestamp, current_timestamp),
(69, '“미안한데…” 하며 미안해하면서 거절', '“미안한데…” 하며 미안해하면서 거절', 4, true, current_timestamp, current_timestamp),
(69, '거절을 못하는 인간.. 결국 수락함', '거절을 못하는 인간.. 결국 수락함', 5, true, current_timestamp, current_timestamp),
(70, '신경도 안 씀, 자기 일은 알아서', '신경도 안 씀, 자기 일은 알아서', 1, true, current_timestamp, current_timestamp),
(70, '봤지만 못 본 척', '봤지만 못 본 척', 2, true, current_timestamp, current_timestamp),
(70, '신경은 쓰이는데 가만히 있음', '신경은 쓰이는데 가만히 있음', 3, true, current_timestamp, current_timestamp),
(70, '슬쩍 옆에 앉아 챙김', '슬쩍 옆에 앉아 챙김', 4, true, current_timestamp, current_timestamp),
(70, '먼저 말 걸어 대화에 끌어들임', '먼저 말 걸어 대화에 끌어들임', 5, true, current_timestamp, current_timestamp),
(71, '절대 못 참고 끝까지 따짐', '절대 못 참고 끝까지 따짐', 1, true, current_timestamp, current_timestamp),
(71, '따질 건 따지고 봄', '따질 건 따지고 봄', 2, true, current_timestamp, current_timestamp),
(71, '아깝지만 그냥 넘어감', '아깝지만 그냥 넘어감', 3, true, current_timestamp, current_timestamp),
(71, '“그럴 수 있지” 하고 받아들임', '“그럴 수 있지” 하고 받아들임', 4, true, current_timestamp, current_timestamp),
(71, '기꺼이 손해를 감수함', '기꺼이 손해를 감수함', 5, true, current_timestamp, current_timestamp),
(72, '발끈해서 받아치고 바로 야차', '발끈해서 받아치고 바로 야차', 1, true, current_timestamp, current_timestamp),
(72, '욱하는 티가남', '욱하는 티가남', 2, true, current_timestamp, current_timestamp),
(72, '덤덤하게 받아드림', '덤덤하게 받아드림', 3, true, current_timestamp, current_timestamp),
(72, '그렇구나 수용함', '그렇구나 수용함', 4, true, current_timestamp, current_timestamp),
(72, '차분히 끝까지 들어주고 공감까지 함', '차분히 끝까지 들어주고 공감까지 함', 5, true, current_timestamp, current_timestamp),
(73, '슬쩍 남한테 떠넘김', '슬쩍 남한테 떠넘김', 1, true, current_timestamp, current_timestamp),
(73, '자연스럽게 발 뺌', '자연스럽게 발 뺌', 2, true, current_timestamp, current_timestamp),
(73, '시키면 그냥 수행은 함', '시키면 그냥 수행은 함', 3, true, current_timestamp, current_timestamp),
(73, '“그럼 내가…” 하고 슬쩍 맡음', '“그럼 내가…” 하고 슬쩍 맡음', 4, true, current_timestamp, current_timestamp),
(73, '“내가 할게” 자청해서 맡음', '“내가 할게” 자청해서 맡음', 5, true, current_timestamp, current_timestamp),
(74, '끝까지 자기 고집굽히지 않음', '끝까지 자기 고집굽히지 않음', 1, true, current_timestamp, current_timestamp),
(74, '웬만해서 굽히지 않고 관철함', '웬만해서 굽히지 않고 관철함', 2, true, current_timestamp, current_timestamp),
(74, '들어보고 상황에 따라 결정함', '들어보고 상황에 따라 결정함', 3, true, current_timestamp, current_timestamp),
(74, '잘 양보해서 마찰을 줄이고자 함', '잘 양보해서 마찰을 줄이고자 함', 4, true, current_timestamp, current_timestamp),
(74, '거의 다 양보해서 아낌없이 주는 나무가 됨', '거의 다 양보해서 아낌없이 주는 나무가 됨', 5, true, current_timestamp, current_timestamp),
(75, '읽씹하고 넘김', '읽씹하고 넘김', 1, true, current_timestamp, current_timestamp),
(75, '“누가 하겠지” 하고 빠짐', '“누가 하겠지” 하고 빠짐', 2, true, current_timestamp, current_timestamp),
(75, '눈치 보다 끝까지 안 나서면 그제야', '눈치 보다 끝까지 안 나서면 그제야', 3, true, current_timestamp, current_timestamp),
(75, '“내가 할까?” 하고 손 듦', '“내가 할까?” 하고 손 듦', 4, true, current_timestamp, current_timestamp),
(75, '바로 “내가 할게” 하고 챙김', '바로 “내가 할게” 하고 챙김', 5, true, current_timestamp, current_timestamp),
(76, '아예 못 알아챔', '아예 못 알아챔', 1, true, current_timestamp, current_timestamp),
(76, '알아도 그냥 넘김', '알아도 그냥 넘김', 2, true, current_timestamp, current_timestamp),
(76, '“어?” 하다가 말함', '“어?” 하다가 말함', 3, true, current_timestamp, current_timestamp),
(76, '“무슨 일 있어?” 하고 물음', '“무슨 일 있어?” 하고 물음', 4, true, current_timestamp, current_timestamp),
(76, '먼저 다가가 살뜰히 챙김', '먼저 다가가 살뜰히 챙김', 5, true, current_timestamp, current_timestamp),
(77, '차갑게 잘라버리고 더이상 안들음', '차갑게 잘라버리고 더이상 안들음', 1, true, current_timestamp, current_timestamp),
(77, '단호하게 “안 돼”', '단호하게 “안 돼”', 2, true, current_timestamp, current_timestamp),
(77, '적당히 둘러대고 거절', '적당히 둘러대고 거절', 3, true, current_timestamp, current_timestamp),
(77, '미안하다며 부드럽게 거절', '미안하다며 부드럽게 거절', 4, true, current_timestamp, current_timestamp),
(77, '미안해하며 다른 방법까지 찾아줌', '미안해하며 다른 방법까지 찾아줌', 5, true, current_timestamp, current_timestamp),
(78, '거의 표현 안 함', '거의 표현 안 함', 1, true, current_timestamp, current_timestamp),
(78, '잘 안 드러냄', '잘 안 드러냄', 2, true, current_timestamp, current_timestamp),
(78, '가끔 표현함', '가끔 표현함', 3, true, current_timestamp, current_timestamp),
(78, '자주 표현함', '자주 표현함', 4, true, current_timestamp, current_timestamp),
(78, '늘 따뜻하게 말로 함', '늘 따뜻하게 말로 함', 5, true, current_timestamp, current_timestamp),
(79, '똑같이 받아쳐 버림', '똑같이 받아쳐 버림', 1, true, current_timestamp, current_timestamp),
(79, '기분 나쁜 티를 팍 냄', '기분 나쁜 티를 팍 냄', 2, true, current_timestamp, current_timestamp),
(79, '속으로만 담아둠', '속으로만 담아둠', 3, true, current_timestamp, current_timestamp),
(79, '“무슨 일 있나” 먼저 헤아림', '“무슨 일 있나” 먼저 헤아림', 4, true, current_timestamp, current_timestamp),
(79, '“그럴 만한 사정 있겠거니” 하고 넘김', '“그럴 만한 사정 있겠거니” 하고 넘김', 5, true, current_timestamp, current_timestamp),
(80, '“절대 손해 못 봐” 하며 버팀', '“절대 손해 못 봐” 하며 버팀', 1, true, current_timestamp, current_timestamp),
(80, '따질 건 따지고 봄', '따질 건 따지고 봄', 2, true, current_timestamp, current_timestamp),
(80, '아깝지만 그냥 넘어감', '아깝지만 그냥 넘어감', 3, true, current_timestamp, current_timestamp),
(80, '“그럴 수도 있지” 하고 받아들임', '“그럴 수도 있지” 하고 받아들임', 4, true, current_timestamp, current_timestamp),
(80, '“내가 손해 보고 말지” 기꺼이 감수', '“내가 손해 보고 말지” 기꺼이 감수', 5, true, current_timestamp, current_timestamp);
